spring.application.name=enescena

# ==========================================
# Base de datos
# ==========================================

spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:enescena}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Santiago

spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA
# ==========================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# Servidor
# ==========================================

server.port=${PORT:8080}

# ==========================================
# Encoding
# ==========================================

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true